### ISSUE TITLE
imdCov branch: for anova_filter and gtest_filter, default comparisons = NULL

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartRqc#190]
Per chat with Lisa and Kelly on 31May2022, we would like the default for the comparisons argument in anova_filter() to be NULL; I believe its already implemented where if null, defines comparisons as all comparisons -- just want to give the argument a default so it lines up with previous implementations and doesn't need to be explicitly defined as NULL

**Comment by evanamartin** [comment]
Resolved with pmartR version 2.0.1
